[package]
name = "rustpad"
version = "0.1.0"
authors = ["Julian Goldsmith <shadow0813@gmail.com>"]
build = "build.rs"

[dependencies]
winapi = "0.2"
user32-sys = "0.2"
kernel32-sys = "0.2"
gdi32-sys = "0.2"
comctl32-sys = "0.2"
comdlg32-sys = "0.2"